### ISSUE TITLE
无法在paper上运行

### ISSUE THREAD

**Issue by HangZhouXZH** [spigotplugins/fakeplayer#127]
我输入fakeplayer add XZH后变成了这样:

[17:36:59 WARN]: Unexpected exception while parsing console command "fakeplayer add XZH 0 61 0"
org.bukkit.command.CommandException: Cannot execute command 'fakeplayer' in plugin FakePlayer v2.1.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by orange114** [comment]
插件没有启用，检查下开服时候的log，应该有插件为何没有启用的错误报告。
