### ISSUE TITLE
1.16.4 - Plugin does nothing

### ISSUE THREAD

**Issue by TheVirusWar** [spigotplugins/fakeplayer#14]
It could be Im missusing it but the console spits out an error, so I assume its an actual issue.
Using latest plugin version (it says so in chat). Plugin loads, accepts commands and opens the GUI. When clicking to add a player, nothing happens, but the console spits this out:

`[15:43:55] [Server thread/INFO]: VirusWar issued server command: /fakeplayer menu
[15:43:55] [Server thread/ERROR]: Could not pass event InventoryClickEvent to FakePlayer v1.7.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2277) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:382) ~[?:?]
        at io.github.portlek.fakeplayer.file.MenuFile$FakePlayers.openAnvil(MenuFile.java:108) ~[?:?]
        at io.github.portlek.fakeplayer.file.provider.ListMenuProvider.lambda$init$4(ListMenuProvider.java:68) ~[?:?]
        at io.github.portlek.smartinventory.handle.BasicHandle.accept(BasicHandle.java:72) ~[?:?]
        at io.github.portlek.smartinventory.handle.BasicHandle.accept(BasicHandle.java:41) ~[?:?]
        at io.github.portlek.smartinventory.icon.BasicIcon.lambda$accept$4(BasicIcon.java:110) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_265]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_265]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_265]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_265]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_265]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_265]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_265]
        at io.github.portlek.smartinventory.icon.BasicIcon.accept(BasicIcon.java:110) ~[?:?]
        at io.github.portlek.smartinventory.listener.InventoryClickListener.lambda$onInventoryClick$0(InventoryClickListener.java:97) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_265]
        at io.github.portlek.smartinventory.listener.InventoryClickListener.onInventoryClick(InventoryClickListener.java:96) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-a19903d-bc6a175]
        ... 18 more`

All I got:
Plugins (2): KeepChunks, FakePlayer
There are 3 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/Eglaios Potion Stacker Beta 1.1.zip (world)]
There are 1 data packs available: [file/Timber_v2.1.0.zip (world)]

Latest spigot jar, compiled from BuildTools.

Hope its on my end, but if its not, I wish you happy bug hunting!

**Comment by portlek** [comment]
the plugin does not support for 1.16_R3 version for now.
