### ISSUE TITLE
plugin does nothing and gave error when installing

### ISSUE THREAD

**Issue by SamLeGgamer** [spigotplugins/fakeplayer#198]
It failed to install or smth error under here.
the only command that works is "/fakeplayer reload" and after thatt it says "&aReload complete" and it did nothing

Error:

[FMCS] 19-9-2023 16:40:07 | : [FakePlayer] Error initializing plugin 'FakePlayer-3.0.4.jar' in folder 'plugins' (Is it up to date?)
[FMCS] 19-9-2023 16:40:07 | java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/FakePlayer-3.0.4.jar
[FMCS] 19-9-2023 16:40:07 | at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:209) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[FMCS] 19-9-2023 16:40:07 | at org.bukkit.plugin.java.JavaPlugin.saveDefaultConfig(JavaPlugin.java:196) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[FMCS] 19-9-2023 16:40:07 | at io.github.portlek.fakeplayer.FakePlayerPlugin.onLoad(FakePlayerPlugin.java:10) ~[FakePlayer-3.0.4.jar:?]
[FMCS] 19-9-2023 16:40:07 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.1.jar:git-Paper-193]
[FMCS] 19-9-2023 16:40:07 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.1.jar:git-Paper-193]
[FMCS] 19-9-2023 16:40:07 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.20.1.jar:git-Paper-193]
[FMCS] 19-9-2023 16:40:07 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-193]
[FMCS] 19-9-2023 16:40:07 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:508) ~[paper-1.20.1.jar:git-Paper-193]
[FMCS] 19-9-2023 16:40:07 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-193]
[FMCS] 19-9-2023 16:40:07 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-193]
[FMCS] 19-9-2023 16:40:07 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-193]
[FMCS] 19-9-2023 16:40:07 | at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by SamLeGgamer** [comment]
i have version 3.0.4
