### ISSUE TITLE
Some errors about mmoitems when using FakePlayer.

### ISSUE THREAD

**Issue by Xniao** [spigotplugins/fakeplayer#21]
This is a fantastic plugin. However, I have some problems when create one player. I have installed the mmoitems before. When I create one player, the console begin reporting errors. Is it possible to solve this problem？I will be disappointed if it is not. Because this is a REALLY wonderful plugin! Looking to your reply. Thank you very much!

[Server thread/WARN]: [MMOItems] Task #2507 for MMOItems v6.3.1 generated an exception
java.lang.NullPointerException: null
	at net.Indyuce.mmoitems.MMOItems.lambda$onEnable$2(MMOItems.java:229) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-296]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-296]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-296]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-296]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-296]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-296]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-296]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Xniao** [comment]
I am not a native English speaker.So there may be some misunderstanding sentence. :)

**Comment by portlek** [comment]
I can't find the issue because the plugin is a premium plugin so I can't find source codes of mmoitems plugin. I think you should ask that issue to the plugin's owner.

**Comment by Xniao** [comment]
That's OK. Thank you for your quick reply!

> I can't find the issue because the plugin is a premium plugin so I can't find source codes of mmoitems plugin. I think you should ask that issue to the plugin's owner.
