### ISSUE TITLE
Problems spamming

### ISSUE THREAD

**Issue by Klimar2** [spigotplugins/fakeplayer#22]
please help. Spaming console every second!(
[05:26:54 WARN]: java.lang.IllegalAccessException: Class com.zeshanaslam.actionhealth.support.PreAction can not access a member of class io.github.portlek.fakeplayer.nms.v1_16_R3.EmptyNetHandler with modifiers "public"
[05:26:54 WARN]:        at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
[05:26:54 WARN]:        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
[05:26:54 WARN]:        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
[05:26:54 WARN]:        at java.lang.reflect.Method.invoke(Method.java:491)
[05:26:54 WARN]:        at com.zeshanaslam.actionhealth.support.PreAction.<init>(PreAction.java:20)
[05:26:54 WARN]:        at com.zeshanaslam.actionhealth.utils.HealthUtil.sendActionBar(HealthUtil.java:269)
[05:26:54 WARN]:        at com.zeshanaslam.actionhealth.utils.HealthUtil.sendHealth(HealthUtil.java:78)
[05:26:54 WARN]:        at com.zeshanaslam.actionhealth.LookThread.run(LookThread.java:57)
[05:26:54 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[05:26:54 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[05:26:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294)
[05:26:54 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[05:26:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[05:26:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[05:26:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[05:26:54 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by portlek** [comment]
the plugin called `actionhealth` is spamming that error, because fake player plugin does not support it.

**Comment by Klimar2** [comment]
thx
