### ISSUE TITLE
is it up tp date error

### ISSUE THREAD

**Issue by n1kkilou** [spigotplugins/fakeplayer#23]
hi been this for a while and its running whith no issue and now when i try to run the server again it has an error called is it up to date?

**Comment by portlek** [comment]
what is the error?

**Comment by n1kkilou** [comment]
" is it up to date? " thats the error

**Comment by portlek** [comment]
could you post the whole error?

**Comment by n1kkilou** [comment]
[11:36:25 ERROR]: [FakePlayer] [ACF] Exception in command: fakeplayer reload
[11:36:25 ERROR]: [FakePlayer] [ACF] java.lang.reflect.InvocationTargetException
[11:36:25 ERROR]: [FakePlayer] [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:36:25 ERROR]: [FakePlayer] [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:36:25 ERROR]: [FakePlayer] [ACF] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.lang.reflect.Method.invoke(Method.java:498)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.commands.BaseCommand.execute(BaseCommand.java:513)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.commands.RootCommand.execute(RootCommand.java:99)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.commands.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[11:36:25 ERROR]: [FakePlayer] [ACF] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060)
[11:36:25 ERROR]: [FakePlayer] [ACF] at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.lang.Thread.run(Thread.java:748)
[11:36:25 ERROR]: [FakePlayer] [ACF] Caused by: java.lang.RuntimeException: Location couldn't parse!
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.file.FakesFile.lambda$null$0(FakesFile.java:46)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.Optional.orElseThrow(Optional.java:290)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.file.FakesFile.lambda$onLoad$1(FakesFile.java:45)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.Iterator.forEachRemaining(Iterator.java:116)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:36:25 ERROR]: [FakePlayer] [ACF] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.file.FakesFile.onLoad(FakesFile.java:48)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.file.FlManaged.load(FlManaged.java:46)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.FakePlayerAPI.reloadPlugin(FakePlayerAPI.java:50)
[11:36:25 ERROR]: [FakePlayer] [ACF] at io.github.portlek.fakeplayer.commands.FakePlayerCommand.reloadCommand(FakePlayerCommand.java:34)
[11:36:25 ERROR]: [FakePlayer] [ACF] ... 26 more

**Comment by portlek** [comment]
the fakes file has the wrong location string
`[11:36:25 ERROR]: [FakePlayer] [ACF] Caused by: java.lang.RuntimeException: Location couldn't parse!`

**Comment by n1kkilou** [comment]
how to to fix it i already reinstall the plugin

**Comment by n1kkilou** [comment]
{
  "fakes": {
    "spyninja1": "world/2783_63,39_00,2527_70/-143_56/15_00",
    "Costic133": "world/2785_18,39_20,2523_32/18_15/38_55",
    "Shadowzz": "world/2783_48,39_20,2523_33/18_15/38_55",
    "wew": {
      "ww": "world/2785_06,39_00,2526_71/-183_90/54_90"
    },
    "404": "world/2784_91,39_00,2525_72/-174_75/9_45",
    "zzzZZ": "world/2785_70,39_20,2525_59/-278_25/48_30",
    "Hero22": "world/2783_30,39_00,2526_04/-58_96/35_40",
    "error": {
      "ze": "world/2783_61,39_00,2527_70/-137_70/19_20"
    },
    "Danger22": "world/2785_70,39_00,2526_51/-232_66/12_45"
  }
}

**Comment by n1kkilou** [comment]
i did not touch it

**Comment by n1kkilou** [comment]
{
  "fakes": {
    "spyninja1": "world/2783_63,39_00,2527_70/-143_56/15_00",
    "Costic133": "world/2785_18,39_20,2523_32/18_15/38_55",
    "Shadowzz": "world/2783_48,39_20,2523_33/18_15/38_55",
    "wew": "world/2785_06,39_00,2526_71/-183_90/54_90",
    "404": "world/2784_91,39_00,2525_72/-174_75/9_45",
    "zzzZZ": "world/2785_70,39_20,2525_59/-278_25/48_30",
    "Hero22": "world/2783_30,39_00,2526_04/-58_96/35_40",
    "Danger22": "world/2785_70,39_00,2526_51/-232_66/12_45",
    "error": "world/2783_61,39_00,2527_70/-137_70/19_20"
    }
}

**Comment by n1kkilou** [comment]
i already fix it, i think everytime ill add another fakeplayers this error will show again
