### ISSUE TITLE
WARN - SPAM console

### ISSUE THREAD

**Issue by WhiTe-Yak** [spigotplugins/fakeplayer#30]
This server is running Paper version git-Paper-534 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

[13:37:57] [Server thread/INFO]: Player1 add fake player success
[13:37:58] [Server thread/WARN]: [WESV] Task #270 for WorldEditSelectionVisualizer v2.0.7 generated an exception
java.lang.IllegalStateException: No player infos loaded for Player1
	at fr.mrmicky.worldeditselectionvisualizer.WorldEditSelectionVisualizer.getPlayerInfos(WorldEditSelectionVisualizer.java:147) ~[?:?]
	at fr.mrmicky.worldeditselectionvisualizer.display.ParticlesTask.run(ParticlesTask.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-534]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-534]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1301) ~[patched_1.16.5.jar:git-Paper-534]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-534]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-534]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Paper-534]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-534]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by WhiTe-Yak** [comment]
A lot of problems after installing this plugin.
Log for analyses:
https://pastebin.com/dah6FYMw

**Comment by WhiTe-Yak** [comment]
Closed with no answer

**Comment by WhiTe-Yak** [comment]
> im just busy, the issue should be open.

Okey, i'm wait
