### ISSUE TITLE
Why 1.18 cannot load

### ISSUE THREAD

**Issue by ACG-j** [spigotplugins/fakeplayer#43]
I build the source code in the dev tree branch and put it in ./plugins cannot be loaded
Error logs are as follows.
Could not load 'plugins\FakePlayer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: tr/com/infumia/infumialib/platform/paper/versionmatched/VersionMatched
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:421) ~[purpur-1.18.jar:git-Purpur-1433]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.reload(CraftServer.java:1016) ~[purpur-1.18.jar:git-Purpur-1433]
	at org.bukkit.Bukkit.reload(Bukkit.java:814) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[purpur-1.18.jar:git-Purpur-1433]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:839) ~[purpur-1.18.jar:git-Purpur-1433]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:543) ~[purpur-1.18.jar:git-Purpur-1433]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:517) ~[purpur-1.18.jar:git-Purpur-1433]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.jar:git-Purpur-1433]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.jar:git-Purpur-1433]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-1433]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: tr/com/infumia/infumialib/platform/paper/versionmatched/VersionMatched
	at io.github.portlek.fakeplayer.FakePlayer.<init>(FakePlayer.java:17) ~[FakePlayer.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: tr.com.infumia.infumialib.platform.paper.versionmatched.VersionMatched
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at io.github.portlek.fakeplayer.FakePlayer.<init>(FakePlayer.java:17) ~[FakePlayer.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
	... 15 more

**Comment by portlek** [comment]
it's not released yet, work in progress.
