### ISSUE TITLE
When I create a fake player, players can not login to server (AuthMe)

### ISSUE THREAD

**Issue by AV8DHI** [spigotplugins/fakeplayer#8]
[20:29:54] [Craft Scheduler Thread - 1100/WARN]: [AuthMe] Plugin AuthMe v5.6.0-SNAPSHOT-b2329 generated an exception whi
le executing task 18305
java.lang.NullPointerException: null
        at fr.xephi.authme.util.PlayerUtils.getPlayerIp(PlayerUtils.java:21) ~[?:?]
        at fr.xephi.authme.process.join.AsynchronousJoin.countOnlinePlayersByIp(AsynchronousJoin.java:204) ~[?:?]
        at fr.xephi.authme.process.join.AsynchronousJoin.validatePlayerCountForIp(AsynchronousJoin.java:192) ~[?:?]
        at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:106) ~[?:?]
        at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:77) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.
12.2-bd3db8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:gi
t-CatServer-1.12.2-bd3db8e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by portlek** [comment]
thanks for the report issue!
